doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: 'mariadb-10.5.8'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
#        Doctrine second level cache is currently disabled because it seems to lead to unexpected issues with
#        acceptation tests. Since this Doctrine function is still in beta, it's maybe safer to wait until they release
#        a stable implementation of it.
#        second_level_cache:
#            enabled: true
#            region_cache_driver:
#                type: pool
#                pool: doctrine_cache.providers.second_level
