admin:
    resource: ../../src/Controller/Admin
    trailing_slash_on_root: false
    type: annotation
    prefix: /admin
front:
    resource: ../../src/Controller/Front
    trailing_slash_on_root: false
    type: annotation
    prefix:
        en: /en
        fr: /fr
default:
    resource: ../../src/Controller/IndexController.php
    type: annotation
kernel:
    resource: ../../src/Kernel.php
    type: annotation
