# Should be used with the docker-base project that can be fetched here:
# https://github.com/spydemon/docker-base
version: '2.0'

services:
  cache:
    container_name: tiroucubo-cache
    expose:
      - "6379"
    hostname: tiroucubo-cache
    image: redis:alpine3.13
    ports:
      - "6401:6379" #Redis is bind to the port 6401 on the host.
    networks:
      - default
  db:
    container_name: tiroucubo-db
    environment:
      - POSTGRES_DB=tiroucubo
      - POSTGRES_PASSWORD=toor
      - POSTGRES_USER=root
    expose:
      - "5432"
    hostname: tiroucubo-db
    image: postgres:13-alpine
    ports:
      - "5440:5432" #Postgres is bind to the port 5440 on the host.
    networks:
      - default
    volumes:
      - ./db/db:/var/lib/postgresql/data
  web:
    container_name: tiroucubo-web
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=tiroucubo.local
    hostname: tiroucubo-web
    image: spydemon/php74-symfony:0.1
    volumes:
      - ..:/var/www
      - ./config/local.env:/var/www/.env
      - home:/root
    networks:
      - base
      - default
  web-test:
    container_name: tiroucubo-web_test
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=tiroucubo-test.local
    hostname: tiroucubo-web_test
    image: spydemon/php74-symfony:0.1
    volumes:
      - ..:/var/www
      - ./config/test.env:/var/www/.env
      - home:/root
    networks:
      - base
      - default
volumes:
  home:
networks:
  base:
    external: true
  default:
